# Lab01_2025712567_TaeGyuRoh

### EX1:Row and Column Slicing

Create a 5x5 numpy array filled with numbers from 1 to 25. Extract the third column and the last row.

In [10]:
# Write Your Code Here!
import numpy as np

array = np.array(range(1,26)).reshape(5,5)
print(f"원본 array : \n{array}")
print()

third_columns = array[:,2]
print(f"세번째 열 : \n{third_columns}")
print()

last_row = array[4]
print(f"마지막 행 : \n{last_row}")

원본 array : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

세번째 열 : 
[ 3  8 13 18 23]

마지막 행 : 
[21 22 23 24 25]


# EX2: Element-wise Multiplication with Broadcasting

Create a 3x3 numpy array where each row is [1, 2, 3]. Multiply this array element-wise by the column vector [1, 2, 3] using broadcasting.

In [11]:
#Write Your Code Here!
x = np.full((3,3), [1,2,3])
y = np.array([1,2,3])

w = x+y
print(w)

[[2 4 6]
 [2 4 6]
 [2 4 6]]
